In [1]:
print(" dipesh rijal ")

 dipesh rijal 


#learn numpy day1

In [2]:
import numpy as np


#creating array using numpy

In [3]:
array1 = np.array([1,2,3,4,5])
array2 = np.arange(1,11)


In [4]:
print(array2)
print(type(array1))
for i in array2:
    print(i)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
1
2
3
4
5
6
7
8
9
10


In [5]:
list1 = [1,2,3,4,5]
print (list1)
print(type(list1))
# convert list into array
c_list = np.array(list1)
print(c_list)

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]


In [6]:
#generate 1 to 10 elements in python and list 
list_range = [i for i in range (1,11)]
print (list_range)
for i in list_range:
    print(i)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
1
2
3
4
5
6
7
8
9
10


convert array to list



In [7]:
array1 = np.array([1,2,3,4,5])
c_list = array1.tolist()
print(c_list)
print(array1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


2d array

In [8]:
array_2d = np.array([[1,2,3],[3,4,5]])
print(array_2d)
print(array_2d.ndim)       



[[1 2 3]
 [3 4 5]]
2


using random in numpy

In [9]:
#rand      generate random values between 0 to 1 
#randn     generate the random values close to 0
#randint   generate the random integer with in the range specified 


In [10]:
rand_array = np.random.rand(4)
print(rand_array)

[0.90139808 0.00643657 0.71596331 0.38197584]


In [11]:
randn_array = np.random.randn(3)
print(randn_array)

[-0.30635106  1.99346793 -1.07198308]


In [12]:
randint_array = np.random.randint(0,100, size = [3,3])      # ----(start=0 , stop=100 , size=5)
print(randint_array)

[[81 41 10]
 [ 3 35 69]
 [24 82 54]]


In [13]:
# #print 2d array using rand 
# rand_arr = np.random.rand(6,8)  # row -6 , column -8
# print(rand_arr)

rand_arr1 = np.random.randn(3,4) 
print(rand_arr1)




[[ 0.85148385 -0.48990736 -0.16310885 -1.17853367]
 [ 1.59554931 -0.50827856  0.04682924  0.78311093]
 [-0.03971795 -0.59866746  0.35451597  0.17145283]]


dimension in array 

In [20]:
array1 = np.array([[[1,2,2,4], [1,2,3,4]],[[1,2,3,4],[1,6,7,8]]])
print(array1)
print(array1.ndim)       #for check dimension of array .ndim



[[[1 2 2 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 6 7 8]]]
3


In [24]:
#to make the array dimension by desire
#ndmin           --------> for add desire dimension
array_d = np.array([1,2,2,4] , ndmin=4)
print(array_d)
print(array_d.ndim)       #for check dimension of array .ndim



[[[[1 2 2 4]]]]
4


some functions in numoy

In [35]:
#zeros
#one
#identity
zero_arr = np.zeros([2,2])
print(zero_arr)

###
zero_arr1 = np.ones([2,2])
print(zero_arr1)



[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [37]:
#identity matrix            ------------> .eye
zero_arr1 = np.eye(10)
print(zero_arr1)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [44]:
#perform additional operation in numpy
array_d = np.array([1,2,2,4])

print(1+array_d)
print(array_d.ndim)   

#not work on list 
# list1 = [1,2,3,4]
# print(2+ list1)


#sum of two array
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,1,3,5])
print("sum of arr1 and arr2 =", arr1+arr2)

print("sub of arr1 and arr2 =", arr1-arr2)

print("mul of arr1 and arr2 =", arr1*arr2)

print("div of arr1 and arr2 =", arr1/arr2)

[2 3 3 5]
1
sum of arr1 and arr2 = [2 3 6 9]
sub of arr1 and arr2 = [ 0  1  0 -1]
mul of arr1 and arr2 = [ 1  2  9 20]
div of arr1 and arr2 = [1.  2.  1.  0.8]


In [46]:
print("dsfref")

dsfref


In [47]:
print("dsfref")

dsfref


In [56]:
arr1 = np.random.randint(1,5,size=[3,3])
arr2 = np.random.randint(1,6,size=[3,3])

print(arr1)
print(arr2)
print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 - arr2)
print(arr1 / arr2)

[[2 4 3]
 [4 2 3]
 [1 4 3]]
[[1 5 5]
 [2 4 3]
 [5 3 5]]
[[3 9 8]
 [6 6 6]
 [6 7 8]]
[[ 2 20 15]
 [ 8  8  9]
 [ 5 12 15]]
[[ 1 -1 -2]
 [ 2 -2  0]
 [-4  1 -2]]
[[2.         0.8        0.6       ]
 [2.         0.5        1.        ]
 [0.2        1.33333333 0.6       ]]


slicing operation in 

In [61]:
#slice (5,6,7)
arr1 = np.arange(10)
print(arr1)

#arrayname[start_value : stop_value: step]
print(arr1 [5:8])

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]


In [69]:
#slice 
arr1 = np.arange(21)


print(arr1 [0:21:2])       #:2 skip one element and print next 


[ 0  2  4  6  8 10 12 14 16 18 20]


In [84]:
#slicing in 2d array  
arr1 = np.array([[1,2,3,4],[3,4,5,6],[3,4,5,6]])



print(arr1) 
print(arr1 [1:3,2:4]) 

[[1 2 3 4]
 [3 4 5 6]
 [3 4 5 6]]
[[5 6]
 [5 6]]


shaping and reshaping in numpy array

In [86]:
arr2d = np.array([[1,2,3,4],[1,2,3,4]])
arr2d.shape


(2, 4)

In [96]:
#reshaping 

arr1d = np.array([1,2,3,4,5,6,7,8,9])
arr1d.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
arr1 = np.random.randni(12)
arr1.reshape(4,3)



array([[ 1.75480498,  1.39091315,  1.23974576],
       [ 1.26874235,  1.52444613,  0.26788229],
       [ 1.55878986, -0.92185718, -1.79142681],
       [ 1.28416426,  1.3243318 , -0.93250467]])

In [103]:
arr1.reshape(12)

array([ 1.75480498,  1.39091315,  1.23974576,  1.26874235,  1.52444613,
        0.26788229,  1.55878986, -0.92185718, -1.79142681,  1.28416426,
        1.3243318 , -0.93250467])

In [107]:
#matrix
mat1 = np.matrix([[1,2,3],[4,5,6]])                #----> 2,3 * 3,2 for matrix multiplication
mat2 = np.matrix([[3,4,5],[6,7,8],[2,3,4]])
mat1*mat2

matrix([[21, 27, 33],
        [54, 69, 84]])